nx667j: Completely drop aptxals framework and related blobs
* This constantly crashes potentially because of the major BT stack
  changes introduced in QRP1. We need to wait for QCOM to pick and
  adapt this changes internally.

E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method isBroadcastActive()Z in class Landroid/bluetooth/BluetoothAdapter;
or its super classes (declaration of 'android.bluetooth.BluetoothAdapter' appears in /apex/com.android.btservices/javalib/framework-bluetooth.jar)

Change-Id: I8a5537122f5487a17af4ddbb6f1febd91ba20245